#############################################################################
# Makefile for building: meego-handset-camera
# Generated by qmake (2.01a) (Qt 4.8.3) on: Tue Oct 8 11:35:13 2013
# Project:  declarative-camera.pro
# Template: app
# Command: /usr/lib/qt4/bin/qmake -o Makefile declarative-camera.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQ_WS_MEEGO -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4 -I/usr/include/QtMultimediaKit -I/usr/include/resource/qt4 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/resource -I/usr/include -I/usr/include/QtMobility -I/usr/X11R6/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -lresourceqt -ldbus-qeventloop -lresource -ldbus-1 -L/usr/lib -lQtMultimediaKit -lQtDeclarative -lQtOpenGL -lQtGui -lQtNetwork -lQtCore -lGLESv2 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		qmlcamerasettings.cpp \
		meegocamera.cpp \
		qdeclarativecamera.cpp \
		qdeclarativecamerapreviewprovider.cpp moc_qmlcamerasettings.cpp \
		moc_meegocamera.cpp \
		qrc_declarative-camera.cpp
OBJECTS       = main.o \
		qmlcamerasettings.o \
		meegocamera.o \
		qdeclarativecamera.o \
		qdeclarativecamerapreviewprovider.o \
		moc_qmlcamerasettings.o \
		moc_meegocamera.o \
		qrc_declarative-camera.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/mobility.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		declarative-camera.pro
QMAKE_TARGET  = meego-handset-camera
DESTDIR       = 
TARGET        = meego-handset-camera

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: declarative-camera.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/mobility.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtMultimediaKit.prl \
		/usr/lib/libQtDeclarative.prl \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile declarative-camera.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/mobility.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtMultimediaKit.prl:
/usr/lib/libQtDeclarative.prl:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile declarative-camera.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/meego-handset-camera1.0.0 || $(MKDIR) .tmp/meego-handset-camera1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/meego-handset-camera1.0.0/ && $(COPY_FILE) --parents qmlcamerasettings.h meegocamera.h qdeclarativecamera_p.h qdeclarativecamerapreviewprovider_p.h .tmp/meego-handset-camera1.0.0/ && $(COPY_FILE) --parents declarative-camera.qrc .tmp/meego-handset-camera1.0.0/ && $(COPY_FILE) --parents main.cpp qmlcamerasettings.cpp meegocamera.cpp qdeclarativecamera.cpp qdeclarativecamerapreviewprovider.cpp .tmp/meego-handset-camera1.0.0/ && (cd `dirname .tmp/meego-handset-camera1.0.0` && $(TAR) meego-handset-camera1.0.0.tar meego-handset-camera1.0.0 && $(COMPRESS) meego-handset-camera1.0.0.tar) && $(MOVE) `dirname .tmp/meego-handset-camera1.0.0`/meego-handset-camera1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/meego-handset-camera1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qmlcamerasettings.cpp moc_meegocamera.cpp moc_qdeclarativecamera_p.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qmlcamerasettings.cpp moc_meegocamera.cpp moc_qdeclarativecamera_p.cpp
moc_qmlcamerasettings.cpp: qmlcamerasettings.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) qmlcamerasettings.h -o moc_qmlcamerasettings.cpp

moc_meegocamera.cpp: meegocamera.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) meegocamera.h -o moc_meegocamera.cpp

moc_qdeclarativecamera_p.cpp: qdeclarativecamera_p.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) qdeclarativecamera_p.h -o moc_qdeclarativecamera_p.cpp

compiler_rcc_make_all: qrc_declarative-camera.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_declarative-camera.cpp
qrc_declarative-camera.cpp: declarative-camera.qrc \
		ZoomControl.qml \
		QuickSettingsPane.qml \
		CaptureControls.qml \
		declarative-camera.qml \
		BottomPane.qml \
		CameraPropertyModel.qml \
		PhotoPreview.qml \
		ImageButton.qml \
		CameraPropertyButton.qml \
		TopPane.qml \
		CameraPropertyPopup.qml \
		images/icon-m-camera-exposure-minus1.svg \
		images/icon-m-camera-flash-always-screen.svg \
		images/icon-m-framework-close.svg \
		images/icon-m-camera-whitebalance-fluorescent-screen.svg \
		images/icon-m-camera-exposure-plus2.svg \
		images/icon-m-camera-exposure-plus17.svg \
		images/icon-m-camera-whitebalance-sunny-screen.svg \
		images/icon-m-camera-exposure-minus17.svg \
		images/icon-m-camera-exposure-plus13.svg \
		images/icon-m-camera-pause.svg \
		images/icon-m-camera-exposure-minus13.svg \
		images/icon-m-camera-exposure-plus07.svg \
		images/icon-m-camera-whitebalance-cloudy-screen.svg \
		images/icon-m-camera-exposure-0.svg \
		images/icon-m-camera-exposure-minus2.svg \
		images/icon-m-camera-flash-red-eye-screen.svg \
		images/icon-m-camera-exposure-plus03.svg \
		images/icon-m-toolbar-camera.svg \
		images/icon-m-camera-exposure-minus07.svg \
		images/icon-m-camera-exposure-minus03.svg \
		images/icon-m-camera-whitebalance-auto-screen.svg \
		images/icon-m-framework-home.svg \
		images/icon-m-camera-pause-indication.svg \
		images/icon-m-camera-video-record.svg \
		images/icon-m-camera-whitebalance-tungsten-screen.svg \
		images/icon-m-camera-video.svg \
		images/icon-m-toolbar-gallery.svg \
		images/icon-m-camera-flash-auto-screen.svg \
		images/icon-m-toolbar-delete.svg \
		images/icon-m-camera-ongoing-recording.svg \
		images/icon-m-camera-exposure-plus1.svg \
		images/icon-m-camera-flash-off-screen.svg \
		images/camera_camera_setting.png
	/usr/lib/qt4/bin/rcc -name declarative-camera declarative-camera.qrc -o qrc_declarative-camera.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp meegocamera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qmlcamerasettings.o: qmlcamerasettings.cpp qmlcamerasettings.h \
		qdeclarativecamera_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlcamerasettings.o qmlcamerasettings.cpp

meegocamera.o: meegocamera.cpp meegocamera.h \
		qdeclarativecamera_p.h \
		qdeclarativecamerapreviewprovider_p.h \
		qmlcamerasettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meegocamera.o meegocamera.cpp

qdeclarativecamera.o: qdeclarativecamera.cpp qdeclarativecamera_p.h \
		qdeclarativecamerapreviewprovider_p.h \
		moc_qdeclarativecamera_p.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qdeclarativecamera.o qdeclarativecamera.cpp

qdeclarativecamerapreviewprovider.o: qdeclarativecamerapreviewprovider.cpp qdeclarativecamerapreviewprovider_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qdeclarativecamerapreviewprovider.o qdeclarativecamerapreviewprovider.cpp

moc_qmlcamerasettings.o: moc_qmlcamerasettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmlcamerasettings.o moc_qmlcamerasettings.cpp

moc_meegocamera.o: moc_meegocamera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_meegocamera.o moc_meegocamera.cpp

qrc_declarative-camera.o: qrc_declarative-camera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_declarative-camera.o qrc_declarative-camera.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_app_icon: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) /home/ramoncin/socam/svn/socam/trunk/apps/meego-de-camera/meegocamera.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_app_icon:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/meegocamera.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_config_file: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/etc/xdg/Nokia/ || $(MKDIR) $(INSTALL_ROOT)/etc/xdg/Nokia/ 
	-$(INSTALL_FILE) /home/ramoncin/socam/svn/socam/trunk/apps/meego-de-camera/meego-handset-camera.conf $(INSTALL_ROOT)/etc/xdg/Nokia/


uninstall_config_file:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/etc/xdg/Nokia/meego-handset-camera.conf
	-$(DEL_DIR) $(INSTALL_ROOT)/etc/xdg/Nokia/ 


install:  install_target install_app_icon install_config_file  FORCE

uninstall: uninstall_target uninstall_app_icon uninstall_config_file   FORCE

FORCE:

